[project]
name = "talk-to-your-website"
version = "0.1.0"
description = "RAG project for a chatbot that retrieves information from a URL and answers acordingly"
authors = [
    {name = "pietro-tanure",email = "pietro.tanure-onnis@ensta-paris.fr"}
]
readme = "README.md"
requires-python = ">=3.12,<4"
dependencies = [
    "python-dotenv (>=1.1.0,<2.0.0)",
    "haystack-ai (~=2.3.0)",
    "fastapi (>=0.115.12,<0.116.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "trafilatura (>=2.0.0,<3.0.0)",
    "nltk (>=3.9.1)",
    "ipykernel (>=6.29.5,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
